# Generated by Django 4.0.4 on 2022-05-17 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='Name',
        ),
    ]
